keosu_gadget_menu_gadget_add:
    pattern:  /views/page/gadget/menugadget/add/{page}/{zone}
    defaults: { _controller: KeosuGadgetMenuGadgetBundle:Edit:add }
    
keosu_gadget_menu_gadget_edit:
    pattern:  /views/page/gadget/menugadget/edit/{page}/{zone}
    defaults: { _controller: KeosuGadgetMenuGadgetBundle:Edit:edit }
      
keosu_menu_gadget_service:
    pattern:  /service/gadget/menu/{gadgetId}/{format}
    defaults: { _controller: KeosuGadgetMenuGadgetBundle:Service:viewOne }
