services:
    keosu.plugin.push.notification:
        class: Keosu\Gadget\PushNotificationBundle\EventListener\ExportListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }
