keosu_event_viewlist:
    pattern:  /content/event
    defaults: { _controller: KeosuDataModelEventModelBundle:View:view }
    
keosu_event_delete:
    pattern:  /content/event/delete/{id}
    defaults: { _controller: KeosuDataModelEventModelBundle:Edit:delete }
    
keosu_event_edit:
    pattern:  /content/event/edit/{id}
    defaults: { _controller: KeosuDataModelEventModelBundle:Edit:edit }
    
keosu_event_add:
    pattern:  /content/event/add
    defaults: { _controller: KeosuDataModelEventModelBundle:Edit:add }
    
keosu_event_service_list:
    pattern:  /service/content/event/event/{format}
    defaults: { _controller: KeosuDataModelEventModelBundle:Service:view }
    
keosu_event_service_view:
    pattern:  /service/content/event/{id}/{format}
    defaults: { _controller: KeosuDataModelEventModelBundle:Service:viewOne }