imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:       ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        url_base: %url_base%

# Assetic Configuration
assetic:
    debug:          true
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          user:     %database_user%
          password: %database_password%
          charset:  UTF8
        dynamic:
          driver:   %database_driver%    # <
          host:     %database_host%      # | Dynamic conf to for readers bundle
          port:     %database_port%      # | Defined in
          dbname:   %database_name%      # | parameters.ini
          user:     %database_user%      # |
          password: %database_password%  # <
          charset:  UTF8

    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection: default
                mappings:
                    KeosuDataModelArticleModelBundle: ~
                    KeosuDataModelMapModelBundle: ~
                    KeosuDataModelPictureModelBundle: ~
                    KeosuCoreBundle: ~
                    KeosuUserBundle: ~
                    FOSUserBundle: ~
                dql:
                    numeric_functions:
                        acos: Keosu\CoreBundle\DQL\Mysql\Acos
                        sin: Keosu\CoreBundle\DQL\Mysql\Sin
                        cos: Keosu\CoreBundle\DQL\Mysql\Cos
                        radians: Keosu\CoreBundle\DQL\Mysql\Radians
        auto_generate_proxy_classes: %kernel.debug%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
# Friends of Symfony User Configuration
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Keosu\UserBundle\Entity\User
  
# TinyMCE Configuration
stfalcon_tinymce:
  include_jquery: true
  tinymce_jquery: true
  selector: ".tinymce"
  language: %locale%
  theme:
    simple:
      theme: "modern"
