parameters:
#    keosu_article.example.class: Keosu\DataModel\ArticleModelBundle\Example

services:
#    keosu_article.example:
#        class: %keosu_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
