services:
#    keosu_gadget_face_book.example:
#        class: Keosu\Gadget\FaceBookBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    Keosu_plugin.facebook.export:
        class: Keosu\Gadget\FaceBookBundle\EventListener\ExportListener
        arguments: [@service_container]
        tags:
            - { name:kernel.event_subscriber }

