keosu_gadget_authentification_gadget_add:
    pattern:  /views/page/gadget/authentificationgadget/add/{page}/{zone}
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Edit:add }
    
keosu_gadget_authentification_gadget_edit:
    pattern:  /views/page/gadget/authentificationgadget/edit/{page}/{zone}
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Edit:edit }

keosu_gadget_article_service_login:
    pattern:  /service/gadget/authentification/{gadgetId}/{format}/login
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Service:login }
