keosu_gadget_authentification_gadget_add:
    pattern:  /views/page/gadget/authentificationgadget/add/{page}/{zone}
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Edit:add }
    
keosu_gadget_authentification_gadget_edit:
    pattern:  /views/page/gadget/authentificationgadget/edit/{page}/{zone}
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Edit:edit }
    
keosu_gadget_article_reset_success:
    pattern:  /resetting/success
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Reset:success }

keosu_gadget_article_service_init:
    pattern:  /service/gadget/authentification/{gadgetId}/{format}/init
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Service:init }

keosu_gadget_article_service_login:
    pattern:  /service/gadget/authentification/{gadgetId}/{format}/login
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Service:login }
    
keosu_gadget_article_service_register:
    pattern:  /service/gadget/authentification/{gadgetId}/{format}/register
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Service:register }

keosu_gadget_article_service_forgotPassword:
    pattern:  /service/gadget/authentification/{gadgetId}/{format}/forgotPassword
    defaults: { _controller: KeosuGadgetAuthentificationGadgetBundle:Service:forgotPassword }
