parameters:
#    keosu_gadget_authentification_gadget.example.class: Keosu\Gadget\AuthentificationGadgetBundle\Example

services:
#    keosu_gadget_authentification_gadget.example:
#        class: %keosu_gadget_authentification_gadget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    keosu.security.authentification_handler:
        class: Keosu\Gadget\AuthentificationGadgetBundle\Handler\AuthentificationHandler
        public: false
        arguments:
            - @router
            - @session
