keosu_core_mainhomepage:
    pattern:  /
    defaults: { _controller: KeosuCoreBundle:MainViews:content }

keosu_core_install_check:
    pattern:  /install
    defaults: { _controller: KeosuCoreBundle:Install:check }

keosu_core_install_configure:
    pattern:  /install/configure
    defaults: { _controller: KeosuCoreBundle:Install:configure }
    
keosu_core_install_installdb:
    pattern:  /install/installdb
    defaults: { _controller: KeosuCoreBundle:Install:installdb }

keosu_core_configuration:
    pattern:  /configuration
    defaults: { _controller: KeosuCoreBundle:MainViews:configuration }
    

keosu_core_homepage:
    pattern:  /content
    defaults: { _controller: KeosuCoreBundle:MainViews:content, appid:0 }
    
keosu_core_page:
    pattern:  /views
    defaults: { _controller: KeosuCoreBundle:MainViews:page }
    requirements:
        _method:  GET
        
keosu_core_publish:
    pattern:  /publish
    defaults: { _controller: KeosuCoreBundle:MainViews:publish }
    requirements:
        _method:  GET
        
keosu_core_views_page_check:
    pattern:  /views/page/check
    defaults: { _controller: KeosuCoreBundle:ManagePages:checkIsMain }
        
keosu_core_views_page_manage:
    pattern:  /views/page/manage
    defaults: { _controller: KeosuCoreBundle:ManagePages:view }
    
keosu_core_views_page_manage_add:
    pattern:  /views/page/manage/add
    defaults: { _controller: KeosuCoreBundle:ManagePages:add }
    
keosu_core_views_page_manage_edit:
    pattern:  /views/page/manage/edit/{id}
    defaults: { _controller: KeosuCoreBundle:ManagePages:edit }
    
keosu_core_views_page_manage_delete:
    pattern:  /views/page/manage/delete/{id}
    defaults: { _controller: KeosuCoreBundle:ManagePages:delete }
    
keosu_core_views_page:
    pattern:  /views/page/{id}
    defaults: { _controller: KeosuCoreBundle:PageStudio:view }
    
keosu_core_app_manage:
    pattern:  /app/manage
    defaults: { _controller: KeosuCoreBundle:ManageApps:view }
    
keosu_core_app_manage_add:
    pattern:  /app/manage/add
    defaults: { _controller: KeosuCoreBundle:ManageApps:add }
    
keosu_core_app_manage_edit:
    pattern:  /app/manage/edit/{id}
    defaults: { _controller: KeosuCoreBundle:ManageApps:edit }
    
keosu_core_theme_manage:
    pattern:  /theme/manage
    defaults: { _controller: KeosuCoreBundle:ManageThemes:view }
    
keosu_core_theme_manage_add:
    pattern:  /theme/manage/add
    defaults: { _controller: KeosuCoreBundle:ManageThemes:add }
    
keosu_core_theme_manage_edit:
    pattern:  /theme/manage/edit/{id}
    defaults: { _controller: KeosuCoreBundle:ManageThemes:edit }
 
keosu_gadget_delete:
    pattern:  /views/page/gadget/delete/{page}/{zone}
    defaults: { _controller: KeosuCoreBundle:GadgetEdit:delete }
    
keosu_ReaderManager_manage:
    pattern:  /content/reader/manage
    defaults: { _controller: KeosuCoreBundle:ManageReaders:add }
    
keosu_ReaderManager_edit_delete:
    pattern:  /content/reader/manage/delete/{id}
    defaults: { _controller: KeosuCoreBundle:ManageReaders:delete }
    
keosu_ReaderManager_service_list:
    pattern:  /service/content/reader/list/{format}
    defaults: { _controller: KeosuCoreBundle:ReaderService:view }  
    
keosu_core_exporter_export:
    pattern:  /publish/export/
    defaults: { _controller: KeosuCoreBundle:Exporter:export }
    
keosu_changeapp:
    pattern:  /changeapp/{appid}
    defaults: { _controller: KeosuCoreBundle:ChangeApp:changeApp }  