parameters:
    keosu_core.exporter.class: Keosu\CoreBundle\Service\Exporter
    keosu_core.curapp.class: Keosu\CoreBundle\Service\CurApp

services:
    keosu_core.exporter:
        class: %keosu_core.exporter.class%
        arguments: [@doctrine,@service_container]
    keosu_core.curapp:
        class: %keosu_core.curapp.class%
        arguments: [@doctrine,@session]
    keosu_core.image_type_extension:
        class: Keosu\CoreBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }
    keosu_core.menuprovider.action_listener:
        class: Keosu\CoreBundle\EventListener\MenuProviderListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
