keosu_location_viewlist:
    pattern:  /content/poi/
    defaults: { _controller: KeosuDataModelMapModelBundle:View:view }
    
keosu_poi_delete:
    pattern:  /content/poi/delete/{id}
    defaults: { _controller: KeosuDataModelMapModelBundle:Edit:delete }
    
keosu_poi_edit:
    pattern:  /content/poi/edit/{id}
    defaults: { _controller: KeosuDataModelMapModelBundle:Edit:edit }
    
keosu_poi_add:
    pattern:  /content/poi/add
    defaults: { _controller: KeosuDataModelMapModelBundle:Edit:add }
