parameters:
#    keosu_gadget_picture_gadget.example.class: Keosu\Gadget\PictureGadgetBundle\Example

services:
#    keosu_gadget_picture_gadget.example:
#        class: %keosu_gadget_picture_gadget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
