keosu_gadget_aroundme_service:
    pattern:  /service/gadget/aroundme/{gadgetId}/{lat}/{lng}/{offset}/{limit}/{format}
    defaults: { _controller: KeosuGadgetAroundMeGadgetBundle:Service:viewList}
    
keosu_gadget_aroundme_service_viewone:
    pattern:  /service/gadget/aroundme/view/{poiid}/{format}
    defaults: { _controller: KeosuGadgetAroundMeGadgetBundle:Service:viewOne}
