parameters:
#    keosu_gadget_around_me_gadget.example.class: Keosu\Gadget\AroundMeGadgetBundle\Example

services:
#    keosu_gadget_around_me_gadget.example:
#        class: %keosu_gadget_around_me_gadget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
