parameters:
#    keosu_data_model_picture_model.example.class: Keosu\DataModel\PictureModelBundle\Example

services:
#    keosu_data_model_picture_model.example:
#        class: %keosu_data_model_picture_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
