keosu_ReaderManager_RssReader_add:
    pattern:  /content/reader/manage/add/rss
    defaults: { _controller: KeosuReaderRssReaderBundle:Edit:add }
    
keosu_ReaderManager_RssReader_edit:
    pattern:  /content/reader/manage/edit/rss/{id}
    defaults: { _controller: KeosuReaderRssReaderBundle:Edit:edit }
    
keosu_ReaderManager_RssReader_sync:
    pattern:  /sync/rss/{id}
    defaults: { _controller: KeosuReaderRssReaderBundle:Sync:sync }

keosu_ReaderManager_RssReader_syncAll:
    pattern:  /sync/rss
    defaults: { _controller: KeosuReaderRssReaderBundle:Sync:syncAll }
