parameters:
#    keosu_reader_rss_reader.example.class: Keosu\Reader\RssReaderBundle\Example

services:
#    keosu_reader_rss_reader.example:
#        class: %keosu_reader_rss_reader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
